apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: frontend-to-recommendationservice-delay-formal
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: frontend
  target:
    mode: all
    selector:
      namespaces:
        - default
      labelSelectors:
        app: recommendationservice
  direction: to
  duration: "300s"
  delay:
    latency: "2000ms"
    correlation: "100"
    jitter: "0ms"