apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: frontend-random-cpu-stress
  namespace: online-boutique
spec:
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: frontend
  stressors:
    cpu:
      workers: 1
      load: 80
  duration: "60s"