apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-memory-cartservice
  namespace: default
  labels:
    experiment: chaos-report
    target: cartservice
    fault-type: stress-memory
spec:
  mode: one
  duration: 3m
  selector:
    namespaces:
      - default
    labelSelectors:
      app: cartservice
  stressors:
    memory:
      workers: 1
      size: 32MiB
